package com.ethernom.maintenance.model

enum class AppRequestState(val type: Byte) {
    ACT_TP_CON_TIMEOUT(0x01),
    ACT_TP_CON_READY(0x02),
    ACT_RESET_FAILURE(0x03),
    ACT_RESET_COMPLETED(0x04),
    ACT_DEBUG_PROCESS_FAILURE(0x05),
    ACT_DEBUG_PROCESS_DATA_RSP(0x06),
    READ_QR_CODE_FAILURE(0x07),
    READ_QR_CODE_COMPLETED(0x08),
    ACT_TIMEOUT_UPDATE_CT(0x09),
    ACT_UPDATE_CT_RES(0x10),
    ACT_DEBUG_PROCESS_COMPLETED(0x11),
    ACT_LOGIN_FAILURE(0x12),
    ACT_LOGIN_COMPLETE(0x13),
    ACT_CONNECTION_FAILED(0x14);
}